// Code generated by the Encore 1.50.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly accounting: accounting.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly company: company.ServiceClient
    public readonly inventory: inventory.ServiceClient
    public readonly purchasing: purchasing.ServiceClient
    public readonly sales: sales.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.accounting = new accounting.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.company = new company.ServiceClient(base)
        this.inventory = new inventory.ServiceClient(base)
        this.purchasing = new purchasing.ServiceClient(base)
        this.sales = new sales.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { balanceSheetReport as api_accounting_balance_sheet_report_balanceSheetReport } from "~backend/accounting/balance_sheet_report";
import { cashBankReport as api_accounting_cash_bank_report_cashBankReport } from "~backend/accounting/cash_bank_report";
import { createAccount as api_accounting_create_account_createAccount } from "~backend/accounting/create_account";
import { createJournalEntry as api_accounting_create_journal_entry_createJournalEntry } from "~backend/accounting/create_journal_entry";
import { deleteAccount as api_accounting_delete_account_deleteAccount } from "~backend/accounting/delete_account";
import { deleteJournalEntry as api_accounting_delete_journal_entry_deleteJournalEntry } from "~backend/accounting/delete_journal_entry";
import { generalLedgerReport as api_accounting_general_ledger_report_generalLedgerReport } from "~backend/accounting/general_ledger_report";
import { listAccounts as api_accounting_list_accounts_listAccounts } from "~backend/accounting/list_accounts";
import { listJournalEntries as api_accounting_list_journal_entries_listJournalEntries } from "~backend/accounting/list_journal_entries";
import { profitLossReport as api_accounting_profit_loss_report_profitLossReport } from "~backend/accounting/profit_loss_report";
import { seedAccounting as api_accounting_seed_data_seedAccounting } from "~backend/accounting/seed_data";
import { trialBalance as api_accounting_trial_balance_trialBalance } from "~backend/accounting/trial_balance";
import { updateAccount as api_accounting_update_account_updateAccount } from "~backend/accounting/update_account";

export namespace accounting {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.balanceSheetReport = this.balanceSheetReport.bind(this)
            this.cashBankReport = this.cashBankReport.bind(this)
            this.createAccount = this.createAccount.bind(this)
            this.createJournalEntry = this.createJournalEntry.bind(this)
            this.deleteAccount = this.deleteAccount.bind(this)
            this.deleteJournalEntry = this.deleteJournalEntry.bind(this)
            this.generalLedgerReport = this.generalLedgerReport.bind(this)
            this.listAccounts = this.listAccounts.bind(this)
            this.listJournalEntries = this.listJournalEntries.bind(this)
            this.profitLossReport = this.profitLossReport.bind(this)
            this.seedAccounting = this.seedAccounting.bind(this)
            this.trialBalance = this.trialBalance.bind(this)
            this.updateAccount = this.updateAccount.bind(this)
        }

        public async balanceSheetReport(params: RequestType<typeof api_accounting_balance_sheet_report_balanceSheetReport>): Promise<ResponseType<typeof api_accounting_balance_sheet_report_balanceSheetReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounting/reports/balance-sheet`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_balance_sheet_report_balanceSheetReport>
        }

        public async cashBankReport(params: RequestType<typeof api_accounting_cash_bank_report_cashBankReport>): Promise<ResponseType<typeof api_accounting_cash_bank_report_cashBankReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounting/reports/cash-bank`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_cash_bank_report_cashBankReport>
        }

        /**
         * Creates a new account in the chart of accounts.
         */
        public async createAccount(params: RequestType<typeof api_accounting_create_account_createAccount>): Promise<ResponseType<typeof api_accounting_create_account_createAccount>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_create_account_createAccount>
        }

        /**
         * Creates a new journal entry with validation for balanced debits and credits.
         */
        public async createJournalEntry(params: RequestType<typeof api_accounting_create_journal_entry_createJournalEntry>): Promise<ResponseType<typeof api_accounting_create_journal_entry_createJournalEntry>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal-entries`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_create_journal_entry_createJournalEntry>
        }

        /**
         * Deletes an account.
         */
        public async deleteAccount(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/accounts/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async deleteJournalEntry(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/journal-entries/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async generalLedgerReport(params: RequestType<typeof api_accounting_general_ledger_report_generalLedgerReport>): Promise<ResponseType<typeof api_accounting_general_ledger_report_generalLedgerReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounting/reports/general-ledger`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_general_ledger_report_generalLedgerReport>
        }

        /**
         * Retrieves all active accounts from the chart of accounts.
         */
        public async listAccounts(): Promise<ResponseType<typeof api_accounting_list_accounts_listAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_list_accounts_listAccounts>
        }

        /**
         * Retrieves all journal entries ordered by entry date.
         */
        public async listJournalEntries(): Promise<ResponseType<typeof api_accounting_list_journal_entries_listJournalEntries>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal-entries`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_list_journal_entries_listJournalEntries>
        }

        public async profitLossReport(params: RequestType<typeof api_accounting_profit_loss_report_profitLossReport>): Promise<ResponseType<typeof api_accounting_profit_loss_report_profitLossReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounting/reports/profit-loss`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_profit_loss_report_profitLossReport>
        }

        /**
         * Seeds the database with sample accounting data.
         */
        public async seedAccounting(): Promise<ResponseType<typeof api_accounting_seed_data_seedAccounting>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounting/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_seed_data_seedAccounting>
        }

        /**
         * Generates a trial balance report as of a specific date.
         */
        public async trialBalance(params: RequestType<typeof api_accounting_trial_balance_trialBalance>): Promise<ResponseType<typeof api_accounting_trial_balance_trialBalance>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                asOfDate: params.asOfDate.toISOString(),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/trial-balance`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_trial_balance_trialBalance>
        }

        /**
         * Updates an account.
         */
        public async updateAccount(params: RequestType<typeof api_accounting_update_account_updateAccount>): Promise<ResponseType<typeof api_accounting_update_account_updateAccount>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                accountCode:     params.accountCode,
                accountName:     params.accountName,
                accountType:     params.accountType,
                isActive:        params.isActive,
                parentAccountId: params.parentAccountId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/accounts/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_accounting_update_account_updateAccount>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createUser as api_auth_create_user_createUser } from "~backend/auth/create_user";
import { deleteUser as api_auth_delete_user_deleteUser } from "~backend/auth/delete_user";
import { listUsers as api_auth_list_users_listUsers } from "~backend/auth/list_users";
import { login as api_auth_login_login } from "~backend/auth/login";
import { logout as api_auth_logout_logout } from "~backend/auth/logout";
import { seedUsers as api_auth_seed_data_seedUsers } from "~backend/auth/seed_data";
import { updateProfile as api_auth_update_profile_updateProfile } from "~backend/auth/update_profile";
import { updateUser as api_auth_update_user_updateUser } from "~backend/auth/update_user";
import { verifyToken as api_auth_verify_token_verifyToken } from "~backend/auth/verify_token";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createUser = this.createUser.bind(this)
            this.deleteUser = this.deleteUser.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.login = this.login.bind(this)
            this.logout = this.logout.bind(this)
            this.seedUsers = this.seedUsers.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.updateUser = this.updateUser.bind(this)
            this.verifyToken = this.verifyToken.bind(this)
        }

        /**
         * Creates a new user.
         */
        public async createUser(params: RequestType<typeof api_auth_create_user_createUser>): Promise<ResponseType<typeof api_auth_create_user_createUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_create_user_createUser>
        }

        public async deleteUser(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all users.
         */
        public async listUsers(): Promise<ResponseType<typeof api_auth_list_users_listUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_list_users_listUsers>
        }

        /**
         * Authenticates a user and returns a session token.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Logs out a user by invalidating their session token.
         */
        public async logout(params: RequestType<typeof api_auth_logout_logout>): Promise<void> {
            await this.baseClient.callTypedAPI(`/auth/logout`, {method: "POST", body: JSON.stringify(params)})
        }

        /**
         * Seeds the database with sample user data.
         */
        public async seedUsers(): Promise<ResponseType<typeof api_auth_seed_data_seedUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_seed_data_seedUsers>
        }

        /**
         * Updates the current user's profile.
         */
        public async updateProfile(params: RequestType<typeof api_auth_update_profile_updateProfile>): Promise<ResponseType<typeof api_auth_update_profile_updateProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/profile`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_update_profile_updateProfile>
        }

        /**
         * Updates a user.
         */
        public async updateUser(params: RequestType<typeof api_auth_update_user_updateUser>): Promise<ResponseType<typeof api_auth_update_user_updateUser>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                email:     params.email,
                firstName: params.firstName,
                isActive:  params.isActive,
                lastName:  params.lastName,
                role:      params.role,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_update_user_updateUser>
        }

        /**
         * Verifies a session token and returns user information.
         */
        public async verifyToken(params: RequestType<typeof api_auth_verify_token_verifyToken>): Promise<ResponseType<typeof api_auth_verify_token_verifyToken>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/verify`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_verify_token_verifyToken>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_company_create_create } from "~backend/company/create";
import { deleteCompany as api_company_delete_deleteCompany } from "~backend/company/delete";
import { list as api_company_list_list } from "~backend/company/list";
import { seedCompanies as api_company_seed_data_seedCompanies } from "~backend/company/seed_data";
import { update as api_company_update_update } from "~backend/company/update";

export namespace company {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteCompany = this.deleteCompany.bind(this)
            this.list = this.list.bind(this)
            this.seedCompanies = this.seedCompanies.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new company.
         */
        public async create(params: RequestType<typeof api_company_create_create>): Promise<ResponseType<typeof api_company_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/companies`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_company_create_create>
        }

        public async deleteCompany(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/companies/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all companies.
         */
        public async list(): Promise<ResponseType<typeof api_company_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/companies`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_company_list_list>
        }

        /**
         * Seeds the database with sample company data.
         */
        public async seedCompanies(): Promise<ResponseType<typeof api_company_seed_data_seedCompanies>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/companies/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_company_seed_data_seedCompanies>
        }

        /**
         * Updates a company.
         */
        public async update(params: RequestType<typeof api_company_update_update>): Promise<ResponseType<typeof api_company_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:         params.address,
                currency:        params.currency,
                email:           params.email,
                fiscalYearStart: params.fiscalYearStart,
                name:            params.name,
                phone:           params.phone,
                taxId:           params.taxId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/companies/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_company_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createCategory as api_inventory_create_category_createCategory } from "~backend/inventory/create_category";
import { createProduct as api_inventory_create_product_createProduct } from "~backend/inventory/create_product";
import { deleteCategory as api_inventory_delete_category_deleteCategory } from "~backend/inventory/delete_category";
import { deleteProduct as api_inventory_delete_product_deleteProduct } from "~backend/inventory/delete_product";
import { listCategories as api_inventory_list_categories_listCategories } from "~backend/inventory/list_categories";
import { listProducts as api_inventory_list_products_listProducts } from "~backend/inventory/list_products";
import { seedInventory as api_inventory_seed_data_seedInventory } from "~backend/inventory/seed_data";
import { updateCategory as api_inventory_update_category_updateCategory } from "~backend/inventory/update_category";
import { updateProduct as api_inventory_update_product_updateProduct } from "~backend/inventory/update_product";
import { updateStock as api_inventory_update_stock_updateStock } from "~backend/inventory/update_stock";

export namespace inventory {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCategory = this.createCategory.bind(this)
            this.createProduct = this.createProduct.bind(this)
            this.deleteCategory = this.deleteCategory.bind(this)
            this.deleteProduct = this.deleteProduct.bind(this)
            this.listCategories = this.listCategories.bind(this)
            this.listProducts = this.listProducts.bind(this)
            this.seedInventory = this.seedInventory.bind(this)
            this.updateCategory = this.updateCategory.bind(this)
            this.updateProduct = this.updateProduct.bind(this)
            this.updateStock = this.updateStock.bind(this)
        }

        /**
         * Creates a new product category.
         */
        public async createCategory(params: RequestType<typeof api_inventory_create_category_createCategory>): Promise<ResponseType<typeof api_inventory_create_category_createCategory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_create_category_createCategory>
        }

        /**
         * Creates a new product.
         */
        public async createProduct(params: RequestType<typeof api_inventory_create_product_createProduct>): Promise<ResponseType<typeof api_inventory_create_product_createProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_create_product_createProduct>
        }

        public async deleteCategory(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/categories/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async deleteProduct(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all product categories.
         */
        public async listCategories(): Promise<ResponseType<typeof api_inventory_list_categories_listCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_list_categories_listCategories>
        }

        /**
         * Retrieves all products with category information.
         */
        public async listProducts(): Promise<ResponseType<typeof api_inventory_list_products_listProducts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_list_products_listProducts>
        }

        /**
         * Seeds the database with sample inventory data.
         */
        public async seedInventory(): Promise<ResponseType<typeof api_inventory_seed_data_seedInventory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/inventory/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_seed_data_seedInventory>
        }

        /**
         * Updates a category.
         */
        public async updateCategory(params: RequestType<typeof api_inventory_update_category_updateCategory>): Promise<ResponseType<typeof api_inventory_update_category_updateCategory>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                name:        params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_update_category_updateCategory>
        }

        /**
         * Updates a product.
         */
        public async updateProduct(params: RequestType<typeof api_inventory_update_product_updateProduct>): Promise<ResponseType<typeof api_inventory_update_product_updateProduct>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                categoryId:       params.categoryId,
                cogsAccountId:    params.cogsAccountId,
                costPrice:        params.costPrice,
                description:      params.description,
                isActive:         params.isActive,
                maxStockLevel:    params.maxStockLevel,
                minStockLevel:    params.minStockLevel,
                name:             params.name,
                productType:      params.productType,
                revenueAccountId: params.revenueAccountId,
                sku:              params.sku,
                unit:             params.unit,
                unitPrice:        params.unitPrice,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_update_product_updateProduct>
        }

        /**
         * Updates product stock and records the movement.
         */
        public async updateStock(params: RequestType<typeof api_inventory_update_stock_updateStock>): Promise<ResponseType<typeof api_inventory_update_stock_updateStock>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                movementType:  params.movementType,
                notes:         params.notes,
                quantity:      params.quantity,
                referenceId:   params.referenceId,
                referenceType: params.referenceType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.productId)}/stock`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_inventory_update_stock_updateStock>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { agingPayablesReport as api_purchasing_aging_payables_report_agingPayablesReport } from "~backend/purchasing/aging_payables_report";
import { createPurchaseOrder as api_purchasing_create_purchase_order_createPurchaseOrder } from "~backend/purchasing/create_purchase_order";
import { createSupplier as api_purchasing_create_supplier_createSupplier } from "~backend/purchasing/create_supplier";
import { createSupplierInvoice as api_purchasing_create_supplier_invoice_createSupplierInvoice } from "~backend/purchasing/create_supplier_invoice";
import { deletePurchaseOrder as api_purchasing_delete_purchase_order_deletePurchaseOrder } from "~backend/purchasing/delete_purchase_order";
import { deleteSupplier as api_purchasing_delete_supplier_deleteSupplier } from "~backend/purchasing/delete_supplier";
import { listPurchaseOrders as api_purchasing_list_purchase_orders_listPurchaseOrders } from "~backend/purchasing/list_purchase_orders";
import { listSupplierInvoices as api_purchasing_list_supplier_invoices_listSupplierInvoices } from "~backend/purchasing/list_supplier_invoices";
import { listSuppliers as api_purchasing_list_suppliers_listSuppliers } from "~backend/purchasing/list_suppliers";
import { paySupplierInvoice as api_purchasing_pay_supplier_invoice_paySupplierInvoice } from "~backend/purchasing/pay_supplier_invoice";
import { seedPurchasing as api_purchasing_seed_data_seedPurchasing } from "~backend/purchasing/seed_data";
import { updatePurchaseOrder as api_purchasing_update_purchase_order_updatePurchaseOrder } from "~backend/purchasing/update_purchase_order";
import { updateSupplier as api_purchasing_update_supplier_updateSupplier } from "~backend/purchasing/update_supplier";

export namespace purchasing {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.agingPayablesReport = this.agingPayablesReport.bind(this)
            this.createPurchaseOrder = this.createPurchaseOrder.bind(this)
            this.createSupplier = this.createSupplier.bind(this)
            this.createSupplierInvoice = this.createSupplierInvoice.bind(this)
            this.deletePurchaseOrder = this.deletePurchaseOrder.bind(this)
            this.deleteSupplier = this.deleteSupplier.bind(this)
            this.listPurchaseOrders = this.listPurchaseOrders.bind(this)
            this.listSupplierInvoices = this.listSupplierInvoices.bind(this)
            this.listSuppliers = this.listSuppliers.bind(this)
            this.paySupplierInvoice = this.paySupplierInvoice.bind(this)
            this.seedPurchasing = this.seedPurchasing.bind(this)
            this.updatePurchaseOrder = this.updatePurchaseOrder.bind(this)
            this.updateSupplier = this.updateSupplier.bind(this)
        }

        public async agingPayablesReport(): Promise<ResponseType<typeof api_purchasing_aging_payables_report_agingPayablesReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchasing/aging-payables-report`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_aging_payables_report_agingPayablesReport>
        }

        /**
         * Creates a new purchase order.
         */
        public async createPurchaseOrder(params: RequestType<typeof api_purchasing_create_purchase_order_createPurchaseOrder>): Promise<ResponseType<typeof api_purchasing_create_purchase_order_createPurchaseOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchase-orders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_create_purchase_order_createPurchaseOrder>
        }

        /**
         * Creates a new supplier.
         */
        public async createSupplier(params: RequestType<typeof api_purchasing_create_supplier_createSupplier>): Promise<ResponseType<typeof api_purchasing_create_supplier_createSupplier>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_create_supplier_createSupplier>
        }

        public async createSupplierInvoice(params: RequestType<typeof api_purchasing_create_supplier_invoice_createSupplierInvoice>): Promise<ResponseType<typeof api_purchasing_create_supplier_invoice_createSupplierInvoice>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchasing/supplier-invoices`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_create_supplier_invoice_createSupplierInvoice>
        }

        public async deletePurchaseOrder(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/purchase-orders/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async deleteSupplier(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/suppliers/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all purchase orders with supplier information.
         */
        public async listPurchaseOrders(): Promise<ResponseType<typeof api_purchasing_list_purchase_orders_listPurchaseOrders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchase-orders`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_list_purchase_orders_listPurchaseOrders>
        }

        public async listSupplierInvoices(): Promise<ResponseType<typeof api_purchasing_list_supplier_invoices_listSupplierInvoices>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchasing/supplier-invoices`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_list_supplier_invoices_listSupplierInvoices>
        }

        /**
         * Retrieves all active suppliers.
         */
        public async listSuppliers(): Promise<ResponseType<typeof api_purchasing_list_suppliers_listSuppliers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_list_suppliers_listSuppliers>
        }

        public async paySupplierInvoice(params: RequestType<typeof api_purchasing_pay_supplier_invoice_paySupplierInvoice>): Promise<ResponseType<typeof api_purchasing_pay_supplier_invoice_paySupplierInvoice>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                amount:             params.amount,
                "bank_account_id":  params["bank_account_id"],
                notes:              params.notes,
                "payment_date":     params["payment_date"],
                "payment_method":   params["payment_method"],
                "reference_number": params["reference_number"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchasing/supplier-invoices/${encodeURIComponent(params.id)}/pay`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_pay_supplier_invoice_paySupplierInvoice>
        }

        /**
         * Seeds the database with sample purchasing data.
         */
        public async seedPurchasing(): Promise<ResponseType<typeof api_purchasing_seed_data_seedPurchasing>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchasing/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_seed_data_seedPurchasing>
        }

        /**
         * Updates a purchase order.
         */
        public async updatePurchaseOrder(params: RequestType<typeof api_purchasing_update_purchase_order_updatePurchaseOrder>): Promise<ResponseType<typeof api_purchasing_update_purchase_order_updatePurchaseOrder>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                notes:  params.notes,
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/purchase-orders/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_update_purchase_order_updatePurchaseOrder>
        }

        /**
         * Updates a supplier.
         */
        public async updateSupplier(params: RequestType<typeof api_purchasing_update_supplier_updateSupplier>): Promise<ResponseType<typeof api_purchasing_update_supplier_updateSupplier>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:      params.address,
                email:        params.email,
                isActive:     params.isActive,
                name:         params.name,
                paymentTerms: params.paymentTerms,
                phone:        params.phone,
                taxId:        params.taxId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_purchasing_update_supplier_updateSupplier>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { agingReceivablesReport as api_sales_aging_receivables_report_agingReceivablesReport } from "~backend/sales/aging_receivables_report";
import { createCustomer as api_sales_create_customer_createCustomer } from "~backend/sales/create_customer";
import { createOrder as api_sales_create_order_createOrder } from "~backend/sales/create_order";
import { deleteCustomer as api_sales_delete_customer_deleteCustomer } from "~backend/sales/delete_customer";
import { deleteOrder as api_sales_delete_order_deleteOrder } from "~backend/sales/delete_order";
import { generateInvoice as api_sales_generate_invoice_generateInvoice } from "~backend/sales/generate_invoice";
import { getInvoice as api_sales_get_invoice_getInvoice } from "~backend/sales/get_invoice";
import { listCustomers as api_sales_list_customers_listCustomers } from "~backend/sales/list_customers";
import { listInvoices as api_sales_list_invoices_listInvoices } from "~backend/sales/list_invoices";
import { listOrders as api_sales_list_orders_listOrders } from "~backend/sales/list_orders";
import { salesReport as api_sales_sales_report_salesReport } from "~backend/sales/sales_report";
import { seedSales as api_sales_seed_data_seedSales } from "~backend/sales/seed_data";
import { updateCustomer as api_sales_update_customer_updateCustomer } from "~backend/sales/update_customer";
import { updateInvoice as api_sales_update_invoice_updateInvoice } from "~backend/sales/update_invoice";
import { updateOrder as api_sales_update_order_updateOrder } from "~backend/sales/update_order";

export namespace sales {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.agingReceivablesReport = this.agingReceivablesReport.bind(this)
            this.createCustomer = this.createCustomer.bind(this)
            this.createOrder = this.createOrder.bind(this)
            this.deleteCustomer = this.deleteCustomer.bind(this)
            this.deleteOrder = this.deleteOrder.bind(this)
            this.generateInvoice = this.generateInvoice.bind(this)
            this.getInvoice = this.getInvoice.bind(this)
            this.listCustomers = this.listCustomers.bind(this)
            this.listInvoices = this.listInvoices.bind(this)
            this.listOrders = this.listOrders.bind(this)
            this.salesReport = this.salesReport.bind(this)
            this.seedSales = this.seedSales.bind(this)
            this.updateCustomer = this.updateCustomer.bind(this)
            this.updateInvoice = this.updateInvoice.bind(this)
            this.updateOrder = this.updateOrder.bind(this)
        }

        public async agingReceivablesReport(params: RequestType<typeof api_sales_aging_receivables_report_agingReceivablesReport>): Promise<ResponseType<typeof api_sales_aging_receivables_report_agingReceivablesReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/reports/aging-receivables`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_aging_receivables_report_agingReceivablesReport>
        }

        /**
         * Creates a new customer.
         */
        public async createCustomer(params: RequestType<typeof api_sales_create_customer_createCustomer>): Promise<ResponseType<typeof api_sales_create_customer_createCustomer>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_create_customer_createCustomer>
        }

        /**
         * Creates a new sales order.
         */
        public async createOrder(params: RequestType<typeof api_sales_create_order_createOrder>): Promise<ResponseType<typeof api_sales_create_order_createOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales-orders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_create_order_createOrder>
        }

        public async deleteCustomer(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/customers/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async deleteOrder(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/sales-orders/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async generateInvoice(params: RequestType<typeof api_sales_generate_invoice_generateInvoice>): Promise<ResponseType<typeof api_sales_generate_invoice_generateInvoice>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/generate-invoice`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_generate_invoice_generateInvoice>
        }

        public async getInvoice(params: { id: number }): Promise<ResponseType<typeof api_sales_get_invoice_getInvoice>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/invoices/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_get_invoice_getInvoice>
        }

        /**
         * Retrieves all active customers.
         */
        public async listCustomers(): Promise<ResponseType<typeof api_sales_list_customers_listCustomers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_list_customers_listCustomers>
        }

        public async listInvoices(): Promise<ResponseType<typeof api_sales_list_invoices_listInvoices>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/invoices`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_list_invoices_listInvoices>
        }

        /**
         * Retrieves all sales orders with customer information.
         */
        public async listOrders(): Promise<ResponseType<typeof api_sales_list_orders_listOrders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales-orders`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_list_orders_listOrders>
        }

        public async salesReport(params: RequestType<typeof api_sales_sales_report_salesReport>): Promise<ResponseType<typeof api_sales_sales_report_salesReport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/reports/sales`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_sales_report_salesReport>
        }

        /**
         * Seeds the database with sample sales data.
         */
        public async seedSales(): Promise<ResponseType<typeof api_sales_seed_data_seedSales>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_seed_data_seedSales>
        }

        /**
         * Updates a customer.
         */
        public async updateCustomer(params: RequestType<typeof api_sales_update_customer_updateCustomer>): Promise<ResponseType<typeof api_sales_update_customer_updateCustomer>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:     params.address,
                creditLimit: params.creditLimit,
                email:       params.email,
                isActive:    params.isActive,
                name:        params.name,
                phone:       params.phone,
                taxId:       params.taxId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_update_customer_updateCustomer>
        }

        public async updateInvoice(params: RequestType<typeof api_sales_update_invoice_updateInvoice>): Promise<ResponseType<typeof api_sales_update_invoice_updateInvoice>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                bankAccountId: params.bankAccountId,
                notes:         params.notes,
                paidAmount:    params.paidAmount,
                status:        params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/invoices/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_update_invoice_updateInvoice>
        }

        /**
         * Updates a sales order.
         */
        public async updateOrder(params: RequestType<typeof api_sales_update_order_updateOrder>): Promise<ResponseType<typeof api_sales_update_order_updateOrder>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                notes:  params.notes,
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales-orders/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sales_update_order_updateOrder>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
